BDOG-2485: adds external link auditing to service commissioning page
hmrc/catalogue-frontend pull request #563
Opened 2023-04-13 11:27 UTC by Tyrpix

2023-04-13 12:40 UTC, colin-lamed commented on conf/app.routes
> +POST       /external-link-audit                                            uk.gov.hmrc.cataloguefrontend.externallinkauditing.ExternalLinkAuditingController.sendAudit()
can we give the endpoint a more generic name (like Controller)

2023-04-13 15:00 UTC, colin-lamed submitted a review, later dismissed

2023-04-18 10:03 UTC, RikSherman requested changes

2023-04-18 10:03 UTC, RikSherman commented on app/views/IndexPage.scala.html
> +                                <td><a id="link-to-blog-post" href="@{blog.url}">@{blog.title}</a></td>
This will create multiple <a .../> with the same id each blog post will need its own id"

2023-04-19 15:57 UTC, RikSherman approved these changes

2023-04-20 10:32 UTC, RikSherman approved these changes

2023-04-20 10:36 UTC, merged